services:
  user-management:
    networks:
        - user-network
    build:
        context: .
        dockerfile: Dockerfile
    env_file:
      - .env-app
    volumes:
      - common:/app/share-resource
  user-db:
    networks:
      - user-network
    build:
      context: postgres
      dockerfile: Dockerfile
    env_file:
      - ./postgres/.env-postgres
    volumes:
      - user_pg:/var/lib/postgresql/data
