# Generated by Django 4.2.13 on 2024-05-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='max_players',
        ),
        migrations.AddField(
            model_name='player',
            name='player_id',
            field=models.IntegerField(default=0),
        ),
    ]
