# Generated by Django 4.2.13 on 2024-05-30 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_player_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracketpair',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brackets', to='api.tournament'),
        ),
    ]
