# Generated by Django 4.2.13 on 2024-05-10 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserManagement',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=16, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=1)),
                ('image', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=255)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score_w', models.IntegerField()),
                ('score_l', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_l', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_l', to='user_app.usermanagement')),
                ('user_w', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_w', to='user_app.usermanagement')),
            ],
        ),
        migrations.CreateModel(
            name='FriendManagement',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_a', to='user_app.usermanagement')),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_b', to='user_app.usermanagement')),
            ],
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_id', to='user_app.usermanagement')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_id', to='user_app.usermanagement')),
            ],
        ),
    ]
