# Generated by Django 4.2.13 on 2024-05-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanagement',
            name='image',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usermanagement',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
