services:
    front-nginx:
        networks:
            - user-network
        build:
            context: nginx
            dockerfile: Dockerfile
        ports:
            - "8443:443"
        volumes:
            - frontend_data:/frontend/
            - ssl_volume:/etc/nginx/ssl
            - common:/share-resource