
services:
  ssl:
    build:
      context: ssl
      dockerfile: Dockerfile
    volumes:
      - ssl_volume:/app/ssl

  frontend:
    restart: always
    extends:
      file: frontend/docker/docker-compose.yml
      service: front-nginx
    environment:
      - PARANOIA=2
    depends_on:
      - ssl
      - user-management
      - pong-game

  vault-service:
    restart: on-failure:10
    extends:
      file: vault/docker/docker-compose.yml
      service: vault-service

  vault-setting:
    restart: on-failure:10
    extends:
      file: vault/docker/docker-compose.yml
      service: vault-setting
    depends_on:
      - ssl
      - vault-service

  user-db:
    restart: always
    extends:
      file: user_management/docker-compose.yml
      service: user-db

  user-management:
    restart: always
    extends:
      file: user_management/docker-compose.yml
      service: user-management
    depends_on:
      - vault-service
      - user-db

  pong-game:
    restart: always
    extends:
      file: pong_game/docker-compose.yml
      service: pong-game
    depends_on:
      - vault-service
      - user-db
  redis:
    restart: always
    extends:
      file: pong_game/docker-compose.yml
      service: redis

volumes:
  ssl_volume:
  frontend_data:
  vault_data:
  user_pg:
  common:
networks:
  user-network:
    driver: bridge
