
services:
  frontend:
    restart: always
    extends:
      file: frontend/docker/docker-compose.yml
      service: front-nginx

  vault-service:
    restart: on-failure:10
    extends:
      file: vault/docker/docker-compose.yml
      service: vault-service

  user-db:
    restart: always
    extends:
      file: user_management/docker/docker-compose.yml
      service: user-db

  user-nginx:
    restart: always
    extends:
      file: user_management/docker/docker-compose.yml
      service: user-nginx

  user-management:
    restart: always
    extends:
      file: user_management/docker/docker-compose.yml
      service: user-management

volumes:
  ssl_volume:
    name: ssl_volume
    driver: local
    driver_opts:
      type: none
      device: ./ssl/cert
      o: bind

  frontend_data:
    name: frontend_data
    driver: local
    driver_opts:
      type: none
      device: ./frontend
      o: bind
      
  user_pg:
    name: user_pg
    driver: local
    driver_opts:
      type: none
      device: ./user_management/docker/postgres/pgdata
      o: bind
  user_srcs:
    name: user_srcs
    driver: local
    driver_opts:
      type: none
      device: ./user_management/srcs
      o: bind

networks:
  transcendence:
    driver: bridge
  user-network:
    driver: bridge
