
services:
  frontend:
    restart: always
    extends:
      file: frontend/docker/docker-compose.yml
      service: front-nginx

  vault-service:
    restart: on-failure:10
    extends:
      file: vault/docker/docker-compose.yml
      service: vault-service

  vault-init:
    restart: on-failure:10
    extends:
      file: vault/docker/docker-compose.yml
      service: vault-init
    depends_on:
      - vault-service

  vault-setting:
    restart: on-failure:10
    extends:
      file: vault/docker/docker-compose.yml
      service: vault-setting
    depends_on:
      - vault-service
      - vault-init

  user-db:
    restart: always
    extends:
      file: user_management/docker/docker-compose.yml
      service: user-db

  user-db-setup:
    restart: on-failure:10
    extends:
      file: user_management/docker/docker-compose.yml
      service: user-db-setup
    depends_on:
      - user-db

  user-nginx:
    restart: always
    extends:
      file: user_management/docker/docker-compose.yml
      service: user-nginx
    depends_on:
      - user-management

  user-management:
    restart: always
    extends:
      file: user_management/docker/docker-compose.yml
      service: user-management
    depends_on:
      - user-db-setup
      - vault-service

volumes:
  ssl_volume:
    name: ssl_volume
    driver: local
    driver_opts:
      type: none
      device: ./ssl/cert
      o: bind

  frontend_data:
    name: frontend_data
    driver: local
    driver_opts:
      type: none
      device: ./frontend/files
      o: bind

  vault_data:
    name: vault_data
    driver: local
    driver_opts:
      type: none
      device: ./vault/data
      o: bind
      
  user_pg:
    name: user_pg
    driver: local
    driver_opts:
      type: none
      device: ./user_management/docker/postgres/pgdata
      o: bind
  user_srcs:
    name: user_srcs
    driver: local
    driver_opts:
      type: none
      device: ./user_management/srcs
      o: bind

  common:
    name: common
    driver: local
    driver_opts:
      type: none
      device: ./common
      o: bind

networks:
  user-network:
    driver: bridge
