
services:
  nginx-docker:
    build: ./nginx/
    container_name: nginx-docker
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - pong_network
    depends_on:
      - backend-docker
      - postgres-docker

  backend-docker:
    build: ./backend/
    container_name: backend-docker
    command: sh -c "python manage.py makemigrations && python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - ./backend/:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres-docker
    networks:
      - pong_network

  postgres-docker:
    image: postgres
    container_name: postgres-docker
    restart: always
    env_file:
      .env-postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - pong_network
    ports:
      - 5432:5432

volumes:
  pg_data:
    name: pg_data
    driver: local
    driver_opts:
      type: none
      device: ./postgres/pgdata
      o: bind

networks:
  pong_network:
    driver: bridge
