services:
    vault-service:
        networks:
            - user-network
        build:
            context: vault
            dockerfile: Dockerfile
        ports:
            - "8201:8201"
        volumes:
            - ./vault/config.hcl:/vault/config/config.hcl
            - vault_data:/vault/file/
            - ssl_volume:/vault/cert
        healthcheck:
            retries: 5
        cap_add:
            - IPC_LOCK
        command: server

    vault-init:
        networks:
            - user-network
        image: hashicorp/vault
        env_file:
            - .env-vault
        volumes:
          - ./init/vault-init.sh:/usr/local/bin/vault-init.sh
          - vault_data:/vault/file/
          - ssl_volume:/vault/cert
        command: /usr/local/bin/vault-init.sh
    
    vault-setting:
        networks:
            - user-network
        build:
            context: setting
            dockerfile: Dockerfile
        env_file:
            - .env-vault
        command: python /app/setting.py
        