services:
    vault-service:
        networks:
            - user-network
        build:
            context: vault
            dockerfile: Dockerfile
        ports:
            - "8201:8201"
        volumes:
            - vault_data:/vault/file/
            - ssl_volume:/vault/cert
        healthcheck:
            retries: 5
        cap_add:
            - IPC_LOCK
        env_file:
            - .env-vault

    vault-setting:
        networks:
            - user-network
        build:
            context: setting
            dockerfile: Dockerfile
        volumes:
            - vault_data:/vault/file/
        env_file:
            - .env-vault
        command: python3 /app/setting.py
