CREATE TABLE IF NOT EXISTS USER_MANAGEMENT (
    USER_ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(16),
    PASSWORD VARCHAR(255),
    NAME VARCHAR(50),
    TYPE CHAR(1),
    IMAGE VARCHAR(255),
    STATUS VARCHAR(30),
    PHONE_NUMBER VARCHAR(255),
    LAST_ACTIVITY TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS MATCH_HISTORY (
    ID SERIAL PRIMARY KEY,
    USER_W INT REFERENCES USER_MANAGEMENT (USER_ID),
    USER_L INT REFERENCES USER_MANAGEMENT (USER_ID),
    SCORE_W INT,
    SCORE_L INT,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CHAT_HISTORY (
    ID SERIAL PRIMARY KEY,
    SENDER_ID INT REFERENCES USER_MANAGEMENT (USER_ID),
    RECEIVER_ID INT REFERENCES USER_MANAGEMENT (USER_ID),
    MESSAGE TEXT,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS FRIEND_MANAGEMENT (
    USER_A INT REFERENCES USER_MANAGEMENT (USER_ID),
    USER_B INT REFERENCES USER_MANAGEMENT (USER_ID),
    ACTION VARCHAR(50),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
