services:
  tournament-management:
    networks:
      - tournament-network
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -C "python manage.py makemigrations && python manage,py migrate"
    volumes:
      - tournament_srcs:/app
      - ssl_volume:/app/ssl
      - common:/app/share-resource
    
  tournament-nginx:
    networks:
      - tournament-network
      - tournament-network
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    volumes:
      - ssl_volume:/etc/nginx/ssl
  
  tournament-db:
    networks:
      -tournament-network
    build:
      context: postgres
      dockerfile: Dockerfile
    env_file:
      - ./postgres/.env-postgres
    volumes:
      - tournament_pg:/var/lib/postgresql/data
  
  tournament-db-setup:
    networks:
      - tournament-network
    image: postgres:16.3
    volumes:
      - tournament_pg:/var/lib/postgresql/data
    entrypoint: [ "bash", "-c", "chmod 755 -R /var/lib/postgresql/data"]
