services:
  mock-communication:
    networks:
        - user-network
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "9999:9999"
    command: sh -c "python manage.py makemigrations && python manage.py migrate --noinput && python3 manage.py runserver 0.0.0.0:9999"
