services:
  pong_game:
    networks:
        - user-network
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8001:8001"
  redis:
    networks:
      - user-network
    build:
      context: redis
      dockerfile: Dockerfile