services:
  pong-game:
    networks:
        - user-network
    env_file:
      - .env-app
    build:
        context: .
        dockerfile: Dockerfile
  redis:
    networks:
      - user-network
    build:
      context: redis
      dockerfile: Dockerfile