services:
    vault-service:
        networks:
            - user-network
        build:
            context: vault
            dockerfile: Dockerfile
        ports:
            - "8201:8201"
        volumes:
            - ssl_volume:/vault/cert
        healthcheck:
            retries: 5
        env_file:
            - .env-vault
        cap_add:
            - IPC_LOCK
        # command: bash
        command: server -dev -dev-root-token-id="00000000-0000-0000-0000-000000000000"

    vault-setting:
        networks:
            - user-network
        build:
            context: setting
            dockerfile: Dockerfile
        env_file:
            - .env-vault
        # command: sleep 10000
        command: python /app/setting.py
        