services:
  user-management:
    networks:
        - user-network
    build:
        context: .
        dockerfile: Dockerfile
    env_file:
      - .env-app
    command: sh -c "python manage.py makemigrations && python manage.py migrate --noinput && gunicorn -c /app/gunicorn.config.py"
    volumes:
        - user_srcs:/app
        - ssl_volume:/app/ssl
        - common:/app/share-resource

  user-nginx:
    networks:
      - user-network
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ssl_volume:/etc/nginx/ssl

  user-db:
    networks:
      - user-network
    build:
      context: postgres
      dockerfile: Dockerfile
    env_file:
      - ./postgres/.env-postgres
    volumes:
      - user_pg:/var/lib/postgresql/data

  user-db-setup:
    networks:
      - user-network
    image: postgres:16.3
    volumes:
      - user_pg:/var/lib/postgresql/data
    entrypoint: [ "bash", "-c", "chmod 755 -R /var/lib/postgresql/data"]
